### ISSUE TITLE
Duplicate of tk

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/tcl-feedstock#3]
This feedstock is a duplicate of `tk` that uses an older version. It's libraries will clash with `tk`'s. Should we remove it and add a version branch to `tk`? Some other solution?

cc @conda-forge/core

**Comment by jerowe** [comment]
I think remove it. I only added it because I didn't realize that included
TCL.

**Comment by jakirkham** [comment]
Alright, will do. Thanks @jerowe.
